/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-background": "#191c1e",
        "on-error": "#ffffff",
        "primary": "#004ac6",
        "primary-container": "#2563eb",
        "tertiary": "#943700",
        "inverse-primary": "#b4c5ff",
        "outline-variant": "#c3c6d7",
        "on-secondary": "#ffffff",
        "tertiary-container": "#bc4800",
        "on-secondary-fixed-variant": "#3f465c",
        "inverse-surface": "#2d3133",
        "on-surface": "#191c1e",
        "secondary": "#565e74",
        "surface-container-high": "#e6e8ea",
        "background": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed": "#dbe1ff",
        "secondary-fixed-dim": "#bec6e0",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffede6",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container": "#eceef0",
        "outline": "#737686",
        "surface-dim": "#d8dadc",
        "surface": "#f7f9fb",
        "on-surface-variant": "#434655",
        "tertiary-fixed-dim": "#ffb596",
        "secondary-container": "#dae2fd",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-tint": "#0053db",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-container": "#5c647a",
        "secondary-fixed": "#dae2fd",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdbcd",
        "on-primary-container": "#eeefff",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed": "#00174b",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary-fixed": "#360f00"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin": "32px",
        "base": "4px",
        "container-max": "1440px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-md": ["Manrope"],
        "display-lg": ["Manrope"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Manrope"],
        "label-bold": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Manrope"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-bold": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
